name: weather_service
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
    sdk: ">=3.0.6 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    firebase_core: ^2.15.1
    firebase_auth: ^4.7.3
    geolocator: ^10.0.0
    dio: ^5.3.2
    flutter_svg: ^2.0.7
    bloc: ^8.1.2
    flutter_bloc: ^8.1.3
    sqflite: ^2.3.0
    path: ^1.8.3
    intl: ^0.18.1
    hive: ^2.2.3
    hive_flutter: ^1.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/svg/
        - assets/png/big-icons/
        - assets/png/small-icons/
    fonts:
        - family: Inter
          fonts:
              - asset: assets/fonts/Inter/Inter-Bold.ttf
              - asset: assets/fonts/Inter/Inter-Light.ttf
        - family: Ubuntu
          fonts:
              - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
              - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
              - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
              - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
              - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
              - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
              - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
              - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
