name: weather_service
description: Flutter Weather App using OpenWeatherMap API and Bloc Pattern.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.11.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  dio: ^5.9.2
  flutter_svg: ^2.2.4
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/big-icons/
    - assets/png/small-icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
